version: "3.1"

services:
  bot:
    image: registry.dev-1.uspenskiy.su:443/yt_downloader_bot:1.0.2
    restart: always
    ports:
      - 9001:80
    environment:
      - ASPNETCORE_URLS=http://*:80
      - BotConfig__Host=${host}
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export BotConfig__Token=$$(cat /run/secrets/TelegramYouTubeBotToken); ./yt_downloader_bot",
      ]
    secrets:
      - TelegramYouTubeBotToken
secrets:
  TelegramYouTubeBotToken:
    external: true