version: "3.1"

services:
  bot:
    image: registry.dev-1.uspenskiy.su:443/yt_downloader_bot:1.0.1
    restart: always
    ports:
      - 9001:80
    environment:
      - PORT=80
      - TokenSecret=${token}
      - BotConfig__Host=${host}
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export BotConfig__Token=$$(cat /var/run/secrets/TokenSecret) ; source /entrypoint.sh",
      ]
